title: 'Telefónica | Dirección de Transformación TI'
default_lang: Perú
author:
  name: 'Joel Ganggini García'
  email: joel.ganggini@telefonica.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Telefónica | Dirección de Transformación TI'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  - Lima
routes: null
blog:
  route: /blog
